### ISSUE TITLE
Critical Error / Try reset Assets

### ISSUE THREAD

**Issue by lordoftheloidl** [siryoav/BeatSaberPlaylistEditor#2]
Tried reinstalling Beatsaber and BMBF but nothing seems to work,
Needed to update my Beat Saber to download more custom songs. The Feature just had a malfunction since the update.

Need some Instructions on how to get this Program up and running again.

**Comment by lordoftheloidl** [comment]
Put Issue in the Wrong Branch

**Comment by siryoav** [comment]
Seems irrelevant to this project.
Locked
